"""enhance_subscriptions_billing_date_icon_description

Revision ID: 57af61b7c978
Revises: 84011e6ac100
Create Date: 2026-03-19 22:08:51.260487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57af61b7c978'
down_revision: Union[str, Sequence[str], None] = '84011e6ac100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_date', sa.Date(), nullable=True))
    op.add_column('subscriptions', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('subscriptions', sa.Column('icon_name', sa.String(length=100), nullable=True))
    op.drop_column('subscriptions', 'billing_day')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_day', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'icon_name')
    op.drop_column('subscriptions', 'description')
    op.drop_column('subscriptions', 'billing_date')
    # ### end Alembic commands ###
