"""subscription_to_transactions

Revision ID: 78abcf9a7f1b
Revises: 57af61b7c978
Create Date: 2026-03-22 19:46:42.591205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78abcf9a7f1b'
down_revision: Union[str, Sequence[str], None] = '57af61b7c978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    transaction_classification = postgresql.ENUM('default', 'subscription', name='transaction_classification')
    transaction_classification.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'icon_name')
    op.drop_column('subscriptions', 'amount')
    op.add_column('transactions', sa.Column('type_of_transaction', transaction_classification, server_default='default', nullable=False))
    op.add_column('transactions', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'subscription_id')
    op.drop_column('transactions', 'type_of_transaction')
    op.add_column('subscriptions', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscriptions', sa.Column('icon_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
    transaction_classification = postgresql.ENUM('default', 'subscription', name='transaction_classification')
    transaction_classification.drop(op.get_bind(), checkfirst=True)
