"""add_multi_tenant_accounts

Revision ID: 7a90b4f84537
Revises: 78abcf9a7f1b
Create Date: 2026-03-24 00:47:25.834783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a90b4f84537'
down_revision: Union[str, Sequence[str], None] = '78abcf9a7f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', 'code'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    op.create_table('account_members',
    sa.Column('role', sa.Enum('OWNER', 'USER', name='account_member_role'), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'code'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id')
    )
    # 1. Adicionar as colunas como nullable=True
    op.add_column('categories', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('created_by', sa.Integer(), nullable=True))

    # 2. Criar a "Conta Pessoal" e popular para os usuários existentes
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, name FROM users")).fetchall()
    
    for user_id, user_name in users:
        # Create an account for the user
        result = connection.execute(
            sa.text("INSERT INTO accounts (name, max_members, is_active) VALUES (:name, :max, :active) RETURNING id"),
            {"name": f"Conta de {user_name}", "max": 5, "active": True}
        )
        account_id = result.fetchone()[0]
        
        # Link user as owner
        connection.execute(
            sa.text("INSERT INTO account_members (account_id, user_id, role, is_accepted) VALUES (:acc, :usr, 'OWNER', true)"),
            {"acc": account_id, "usr": user_id}
        )
        
        # Update existing records
        connection.execute(
            sa.text("UPDATE categories SET account_id = :acc WHERE user_id = :usr"),
            {"acc": account_id, "usr": user_id}
        )
        connection.execute(
            sa.text("UPDATE subscriptions SET account_id = :acc WHERE user_id = :usr"),
            {"acc": account_id, "usr": user_id}
        )
        connection.execute(
            sa.text("UPDATE transactions SET account_id = :acc, created_by = :usr WHERE user_id = :usr"),
            {"acc": account_id, "usr": user_id}
        )

    # 3. Mudar as colunas para nullable=False
    op.alter_column('categories', 'account_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('subscriptions', 'account_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('transactions', 'account_id', existing_type=sa.Integer(), nullable=False)
    op.alter_column('transactions', 'created_by', existing_type=sa.Integer(), nullable=False)

    # 4. Criar ForeignKey constraints
    op.create_foreign_key('fk_categories_account_id', 'categories', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_subscriptions_account_id', 'subscriptions', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_transactions_created_by', 'transactions', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_transactions_account_id', 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_transactions_account_id', 'transactions', type_='foreignkey')
    op.drop_constraint('fk_transactions_created_by', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'created_by')
    op.drop_column('transactions', 'account_id')
    op.drop_constraint('fk_subscriptions_account_id', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'account_id')
    op.drop_constraint('fk_categories_account_id', 'categories', type_='foreignkey')
    op.drop_column('categories', 'account_id')
    op.drop_table('account_members')
    op.drop_table('accounts')
    # ### end Alembic commands ###
