"""add_recurrence_id_to_transactions

Revision ID: 84011e6ac100
Revises: eb66a5691374
Create Date: 2026-03-19 22:03:50.724650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84011e6ac100'
down_revision: Union[str, Sequence[str], None] = 'eb66a5691374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('recurrence_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_transactions_recurrence_id'), 'transactions', ['recurrence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_recurrence_id'), table_name='transactions')
    op.drop_column('transactions', 'recurrence_id')
    # ### end Alembic commands ###
