"""add owner_id to transactions

Revision ID: bf0587e8b1c4
Revises: c9f2a4b1d8e7
Create Date: 2026-03-30 22:53:19.466327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0587e8b1c4'
down_revision: Union[str, Sequence[str], None] = 'c9f2a4b1d8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credit_cards_account_id'), table_name='credit_cards')
    op.drop_index(op.f('ix_credit_cards_code'), table_name='credit_cards')
    op.create_unique_constraint(None, 'credit_cards', ['id'])
    op.drop_index(op.f('ix_invoices_code'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_credit_card_id'), table_name='invoices')
    op.create_unique_constraint(None, 'invoices', ['id'])
    op.add_column('transactions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_transactions_invoice_id'), table_name='transactions')
    op.create_foreign_key(None, 'transactions', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_index(op.f('ix_transactions_invoice_id'), 'transactions', ['invoice_id'], unique=False)
    op.drop_column('transactions', 'owner_id')
    op.drop_constraint(None, 'invoices', type_='unique')
    op.create_index(op.f('ix_invoices_credit_card_id'), 'invoices', ['credit_card_id'], unique=False)
    op.create_index(op.f('ix_invoices_code'), 'invoices', ['code'], unique=False)
    op.drop_constraint(None, 'credit_cards', type_='unique')
    op.create_index(op.f('ix_credit_cards_code'), 'credit_cards', ['code'], unique=False)
    op.create_index(op.f('ix_credit_cards_account_id'), 'credit_cards', ['account_id'], unique=False)
    # ### end Alembic commands ###
