FROM python:3.12-slim-trixie

# deps mínimas para instalar o uv
RUN apt-get update \
 && apt-get install -y --no-install-recommends curl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

# instala o uv (binário vai para ~/.local/bin)
RUN curl -LsSf https://astral.sh/uv/0.8.19/install.sh | sh
ENV PATH="/root/.local/bin:$PATH"

# venv do projeto DENTRO do container (não é montada)
ENV UV_PROJECT_ENVIRONMENT=/opt/uv/venv
ENV PATH="/opt/uv/venv/bin:$PATH"

WORKDIR /app

ENV PYTHONPATH="/app:$PYTHONPATH"

COPY pyproject.toml uv.lock* ./

RUN uv sync

COPY . /app

ENTRYPOINT []
CMD ["uv", "run", "main.py"]
